# -*- coding: utf-8 -*-
"""Hospital_chatbot.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WCZbxW4zAjJYb4xAryzc2PCXA3gfGxWC
"""

import aiml

# Create the kernel and learn AIML files
kernel = aiml.Kernel()
kernel.learn('/content/hospitalChatbot3.xml')
kernel.respond("load prac2")

pip install python-aiml

import aiml

kernel = aiml.Kernel()
kernel.learn("/content/hospitalChatbot3.xml")
kernel.respond("load prac 2")

while True:
    input_text= input(">Human: ")
    response =kernel.respond(input_text)
    print(">Bot: "+response)

